### ISSUE TITLE
Suivi Hackathon DBD2 - Aks?

### ISSUE THREAD

**Issue by daoodaba975** [HimmaAtos/BitArt#5]
Hello @HimmaAtos @awa-faye @Dia-Thiane 

J'ai remarqué que vous avancer bien sûr les deux parties, j'ai testé le front en Flutter.
Dans sa globalité comment comptez-vous faire fonctionner le projet étant donné que vous avez 2 repos séparés ?

**Comment by HimmaAtos** [comment]
pour l'instant on démarre les deux solutions en local. Mais nous sommes entrain de déployer la partie backend pour permettre au gens qui ont le front de pouvoir tester directement sans pour autant avoir le backend

**Comment by daoodaba975** [comment]
Ok, d'accord je vois, ça marche.

**Comment by daoodaba975** [comment]
Hello @HimmaAtos vous avez du nouveau sur le déploiement de la partie backend ?

**Comment by HimmaAtos** [comment]
Hello @daoodaba975 
Oui on est sur ça jusque la. On rencontre des problémes  mais on continue. Néanmoins vous pouvez aussi la démarrer en local.

**Comment by daoodaba975** [comment]
Ok d'accord !

**Comment by HimmaAtos** [comment]
Bonjour @daoodaba975 
On a reussi finalement à deployer le backend. Voici le lien :[https://bitart.pythonanywhere.com/]

**Comment by HimmaAtos** [comment]
Vous pouvez toujours suivre l'évolution de l'application du coté backend comme frontend seulement dans les branches main. Nous nous assurons que ces branches soient à jours pour des éventuelles testes de votre part.
Merci

**Comment by daoodaba975** [comment]
Super!
